export const ACTION_SUFFIX_REQUESTED = 'REQUESTED';
export const ACTION_SUFFIX_SUCCEEDED = 'SUCCEEDED';
export const ACTION_SUFFIX_FAILED = 'FAILED';
export const ACTION_SUFFIX_NORMALIZED = 'NORMALIZED';

export const ACTION_SUFFIXES = [
  ACTION_SUFFIX_REQUESTED,
  ACTION_SUFFIX_SUCCEEDED,
  ACTION_SUFFIX_FAILED,
  ACTION_SUFFIX_NORMALIZED,
];
