export const API_REQUEST_SUFFIX_REQUESTED = 'REQUESTED';
export const API_REQUEST_SUFFIX_SUCCEEDED = 'SUCCEEDED';
export const API_REQUEST_SUFFIX_FAILED = 'FAILED';

export const API_REQUEST_SUFFIXES = [
  API_REQUEST_SUFFIX_REQUESTED,
  API_REQUEST_SUFFIX_SUCCEEDED,
  API_REQUEST_SUFFIX_FAILED,
];
